# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import vad_pb2 as vad__pb2
except ImportError:
    import vad_pb2 as vad__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vad_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VADServiceStub(object):
    """VAD Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/vad.VADService/CreateSession',
                request_serializer=vad__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=vad__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.Detect = channel.unary_unary(
                '/vad.VADService/Detect',
                request_serializer=vad__pb2.DetectRequest.SerializeToString,
                response_deserializer=vad__pb2.DetectResponse.FromString,
                _registered_method=True)
        self.ResetSession = channel.unary_unary(
                '/vad.VADService/ResetSession',
                request_serializer=vad__pb2.ResetSessionRequest.SerializeToString,
                response_deserializer=vad__pb2.Empty.FromString,
                _registered_method=True)
        self.DestroySession = channel.unary_unary(
                '/vad.VADService/DestroySession',
                request_serializer=vad__pb2.DestroySessionRequest.SerializeToString,
                response_deserializer=vad__pb2.Empty.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/vad.VADService/GetStats',
                request_serializer=vad__pb2.Empty.SerializeToString,
                response_deserializer=vad__pb2.StatsResponse.FromString,
                _registered_method=True)


class VADServiceServicer(object):
    """VAD Service Definition
    """

    def CreateSession(self, request, context):
        """Create a new VAD session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Detect(self, request, context):
        """Detect voice activity in audio data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetSession(self, request, context):
        """Reset session state (clear buffers)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroySession(self, request, context):
        """Destroy a VAD session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Get service stats
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VADServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=vad__pb2.CreateSessionRequest.FromString,
                    response_serializer=vad__pb2.CreateSessionResponse.SerializeToString,
            ),
            'Detect': grpc.unary_unary_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=vad__pb2.DetectRequest.FromString,
                    response_serializer=vad__pb2.DetectResponse.SerializeToString,
            ),
            'ResetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetSession,
                    request_deserializer=vad__pb2.ResetSessionRequest.FromString,
                    response_serializer=vad__pb2.Empty.SerializeToString,
            ),
            'DestroySession': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroySession,
                    request_deserializer=vad__pb2.DestroySessionRequest.FromString,
                    response_serializer=vad__pb2.Empty.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=vad__pb2.Empty.FromString,
                    response_serializer=vad__pb2.StatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vad.VADService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vad.VADService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VADService(object):
    """VAD Service Definition
    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vad.VADService/CreateSession',
            vad__pb2.CreateSessionRequest.SerializeToString,
            vad__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vad.VADService/Detect',
            vad__pb2.DetectRequest.SerializeToString,
            vad__pb2.DetectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vad.VADService/ResetSession',
            vad__pb2.ResetSessionRequest.SerializeToString,
            vad__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroySession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vad.VADService/DestroySession',
            vad__pb2.DestroySessionRequest.SerializeToString,
            vad__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vad.VADService/GetStats',
            vad__pb2.Empty.SerializeToString,
            vad__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
